version: '3'
services:
  my-transactions-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mongodb:/data/db
    command: mongod --bind_ip_all

  rabbitmq:
    image: rabbitmq:management
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    
